wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    start_time: 1647209522
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 17
      4: 3.6.8
      5: 0.12.11
      8:
      - 5
